# Generated by Django 3.2.9 on 2021-11-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Elementary'), (4, 'Advanced'), (0, 'Starter'), (3, 'Intermediate'), (2, 'Beginner'), (5, 'Expert')], verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
