# Generated by Django 3.2.9 on 2021-12-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_alter_question_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=30, unique=True, verbose_name='Title'),
        ),
    ]
