# Generated by Django 3.2.9 on 2021-11-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_auto_20211126_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Advanced', 'Advanced'), ('Elementary', 'Elementary'), ('Intermediate', 'Intermediate'), ('Beginner', 'Beginner'), ('Expert', 'Expert')], max_length=20, verbose_name='Difficulty'),
        ),
    ]
