# Generated by Django 3.2.9 on 2021-12-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_alter_question_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('Elementary', 'Elementary'), ('Beginner', 'Beginner'), ('Expert', 'Expert'), ('Intermediate', 'Intermediate'), ('Starter', 'Starter'), ('Advanced', 'Advanced')], max_length=20, verbose_name='Difficulty'),
        ),
    ]
